# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pandasmore',
                'doc_host': 'https://ionmihai.github.io',
                'git_url': 'https://github.com/ionmihai/pandasmore',
                'lib_path': 'pandasmore'},
  'syms': {'pandasmore.core': {'pandasmore.core.foo': ('core.html#foo', 'pandasmore/core.py')}}}
