# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pandasmore',
                'doc_host': 'https://ionmihai.github.io',
                'git_url': 'https://github.com/ionmihai/pandasmore',
                'lib_path': 'pandasmore'},
  'syms': { 'pandasmore.core': { 'pandasmore.core.fast_lag': ('core.html#fast_lag', 'pandasmore/core.py'),
                                 'pandasmore.core.lag': ('core.html#lag', 'pandasmore/core.py')}}}
